spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/adego?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api
