spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/adego?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    generate-ddl: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api
