spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adego?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      username: root
      password: phj@3473

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id:
#            client-secret:
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#            authorization-grant-type: authorization_code
#            client-name: google
#            scope:
#              - profile
#              - email
#          apple:
#            client-id: {애플로부터 받은clientId}
#            client-secret: {애플로부터 받은 key 파일}.p8
#            redirect-uri: http://localhost:8080/login/oauth2/code/apple
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST
#            client-name: Apple
#            scope:
#              - name
#              - email
          kakao:
            client-id: d1a76fca632e9b7d19fdc8b357340cc5
            client-secret: 43E8cILng7dMWiy5GoGUj5TspXjCEtAI
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - friends
              - talk_message
            provider: kakao
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token.
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
